### ISSUE TITLE
Not working with latest version of pymodbus

### ISSUE THREAD

**Issue by LeskoIam** [jernejnose/iskra-WM3M4C-controller#2]
Not working with pymodbus==3.6.8

Can you please add requirements.txt and add versions with which it's working?

Thank you very much!

**Comment by LeskoIam** [comment]
Created merge request #3 with fix.

**Comment by jernejnose** [comment]
Resolved in [#3 ](https://github.com/jernejnose/iskra-WM3M4C-controller/pull/3)
